solvers:
  mcts_baseline:
    type: mcts
    initial_guesses: 
      - slate
      - crane
      - slant
      - trace
      - crate
      - carte
    exploration_constant: 10.0
    max_simulations: 100
    n_games: 50
    word_file: valid-wordle-words.txt