solvers:
  mcts_baseline:
    type: mcts
    initial_guesses: 
      - slate
      - crane
      - slant
      - trace
      - crate
      - carte
    alpha: 1000.0
    beta: 10000.0
    max_simulations: 20 # Maximum number of MC simulations to run at each depth
    n_games: 10 # Number of games to play
    word_file: valid-wordle-words.txt